# Server Configuration
server.port=8080

# Spring Data MongoDB Configuration
# Connection string retrieved securely from environment variables
spring.data.mongodb.uri=${MONGODB_URI}
spring.data.mongodb.database=${MONGODB_DB}

# Security and Logging configuration (optional defaults)
logging.level.org.springframework.security=INFO
